# Generated by Django 5.0.3 on 2024-04-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_remove_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.CharField(default='board_container_bottom_todo', max_length=30),
        ),
    ]
