# Generated by Django 5.0.3 on 2024-04-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_task_subtasks_alter_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subtasks',
            new_name='subtask',
        ),
    ]
