# Generated by Django 5.0.3 on 2024-04-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_rename_subtasks_task_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subtask',
            new_name='subtasks',
        ),
    ]
