# Generated by Django 5.0.3 on 2024-04-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_rename_subtask_task_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(default=None, null=True, to='Backend.subtask'),
        ),
    ]
