# Generated by Django 5.0.3 on 2024-04-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_alter_task_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.CharField(default='board_container_bottom_todo', max_length=50),
        ),
    ]
